No longer run the plone.app.event tests.
Also, run the Python 3.11 tests with the latest Python 3.11, instead of a release candidate.

In the last two weekly cron tests, the plone tests fail with:

    ModuleNotFoundError: No module named 'plone.app.event'

I see the same locally.  I have no idea why.  But this seems a good time to stop running the `plone.app.event` tests within `icalendar`.